### PR TITLE
Evict and delete nodes from the master to avoid warnings

### LINKED ISSUE #105: clarify what happens during cleanup
several warnings are presented during a "--provision-with cleanup"

for example

1) k8s-master-1.k8s-p9.local: W0323 01:35:19.650319   18139 removeetcdmember.go:61] [reset] failed to remove etcd member: error syncing endpoints with etc: etcdclient: no available endpoints
    k8s-master-1.k8s-p9.local: .Please manually remove this etcd member using etcdctl

2) The reset process does not clean CNI configuration. To do so, you must remove /etc/cni/net.d

at least we should also output a message saying that we have taken care and that this is not an issue

### PR DESCRIPTION
**Pull request by ferrarimarco**
This PR enriches the cleanup provisioner by evicting nodes and deleting them from the cluster when running on the master.

This avoids warnings when resetting the master and ensures that we don't lose track of the workloads that are deployed on worker nodes, leading to a resource waste.

Closes #105

### CODE REVIEW

File: scripts/linux/cleanup-k8s-and-cni.sh [hunk 1]
```diff
@@ -1,31 +1,51 @@
...
-KUBE_CONFIG_PATH="$HOME/.kube"
 [ -d "$KUBE_CONFIG_PATH" ] && rm -rf "$KUBE_CONFIG_PATH"
-echo "Manually cleaned up $KUBE_CONFIG_PATH"
+echo "Deleted $KUBE_CONFIG_PATH"
 unset KUBE_CONFIG_PATH
 
 KUBE_CONFIG_VAGRANT_PATH="/home/vagrant/.kube"
 [ -d "$KUBE_CONFIG_VAGRANT_PATH" ] && rm -rf "$KUBE_CONFIG_VAGRANT_PATH"
-echo "Manually cleaned up $KUBE_CONFIG_PATH"
+echo "Deleted $KUBE_CONFIG_PATH"
```
Comment (StefanoSalsano) [inline scripts/linux/cleanup-k8s-and-cni.sh:40]: KUBE_CONFIG_VAGRANT_PATH

(copy paste issue...)

Comment (ferrarimarco) [reply scripts/linux/cleanup-k8s-and-cni.sh]: fixed!
